
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS open_to_work BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS seeking_type TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS work_mode TEXT DEFAULT '';

ALTER TABLE public.experience
ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT false;
